# -*- coding: utf-8 -*-
"""edit_distance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GRUva2ZQbpbQGa-JZx3H1Tc1MmekMlo0

# JESSE ANNAN
# 002708111
# ASSIGNMENT 2
"""

def myEditList(aStr, bStr):

  from numpy import array,zeros,arange
  n, m = len(aStr), len(bStr)

  mat1 = array(zeros((n+1,m+1)))
  for i in arange(n+1):
    mat1[i,0] = i
  for j in arange(m+1):
    mat1[0,j] = j

  for i in arange(1,n+1):
    for j in arange(1,m+1):
      if aStr[i-1] == bStr[j-1]:
        mat1[i,j] = mat1[i-1,j-1]
      else:
        #cost = 1
        insertion = mat1[i,j-1] + 1
        deletion = mat1[i-1,j] + 1
        substitution = mat1[i-1,j-1] + 1
        mat1[i,j] = min(insertion, deletion, substitution)  

  return mat1[n,m], mat1

print(myEditList('kitten', 'sitting'))
print(myEditList('gumbo', 'gambol'))